<a href="https://colab.research.google.com/github/prgmr99/machine_learning-sklearn/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ndarray 개념

Numpy는 과학 컴퓨팅을 위한 기본 패키지.

다차원 배열 객체, 이로부터 유도한 마스크된 배열 및 행렬 등과 같은 객체, 논리, 배열 형태 조작, 정렬, 선택, I/O를 비롯한 배열에 대한 빠른 작업을 위한 다양한 루틴을 제공한다.

이외에도 이산 푸리에 변환, 기본 선형 대수학, 기본 통계 연산, 무작위 시뮬레이션 등등 다양한 기능을 가지고 있다.

In [ ]:
# Numpy와 패키지의 핵심은 ndarray 객체이다.
# ndarray는 fixed-size homogeneous multidimensional array 정도로 이해할 수 있다.
# 기본적으로 vectorization 과 broadcasting을 지원


Python에서 제공하는 list, tuple 등의 시퀀스 자료형은 서로 다른 데이터타입을 저장할 수 있고
(heterogeneous sequence), 크기가 자동으로 커질 수 있다.

반면에 ndarray는 성능향상을 위해 같은 데이터타입만을 요소로 가질 수 있고, 크기 역시 고정되어 있다.
만약 크기를 변경하면 새로 메모리에 할당되고 이전 값은 삭제된다.

In [ ]:
# ndarray는 list나 tuple 같은 시퀀스 자료형으로부터 생성한다.
import numpy as np
x=np.array((0.1,0.2,0.3))
x

array([0.1, 0.2, 0.3])

In [ ]:
x.shape

(3,)

In [ ]:
x.dtype

dtype('float64')

In [ ]:
y=np.array(((1,2,3),(4,5,6)))
y

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y.dtype

dtype('int64')

In [ ]:
y.shape

(2, 3)

In [ ]:
# x는 float64를 요소 타입으로 갖는 크기 3의 1차원 배열
# y는 int32을 요소 타입으로 하는 (2,3) 크기의 2차원 배열
# 요소 타입을 dtype 멤버에서 확인할 수 있으며, 차원 shape에서 확인할 수 있다.
# 1차원 배열의 shape은 (m,) 형태이고, 2차원 배열은 (m,n) 형태이다. 3차원은 (p,q,r)등과 같다.
# 생성시 입력된 값을 통해 dtype을 추정하는데, 강제로 지정하는 것은 다음과 같다.
z=np.array([1,2,3], dtype='float64')

narray의 중요 속성

*   shape: 배열의 형태
*   dtype: 요소의 데이터 타입, int32, float32 등등
*   ndim: 차원수. x.ndim=1, y.ndim=2 등이며 len(x.shape)와 동일
*   size: 요소의 개수. shape의 모든 값의 곲. x.size=3, y.size=6 등
*   itemsize: 요소 데이터 타입의 크기(byte 단위), x.itemsize=8 등
*   data: 실제 데이터, 직접 사용자가 접근할 필요는 없다.







**초기화 관련 편의함수**

zeros()는 모두 0으로 초기화한다.

ones()는 모두 1로 초기화한다.

empty()는 값을 초기화하지 않고(메모리 상태에 따라 다른 값이 들어감) 생성한다.

인자로 생성할 배열의 차원을 list, tuple로 지정한다.

dtype은 디폴트가 float64이고, 변경을 원하면 지정해야한다.

In [ ]:
Y=np.zeros((3,3))
Y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
Y=np.ones((3,3),dtype='int32')
Z=np.empty((3,3))

In [ ]:
# 미리 크기를 지정하지 않고 순차적으로 만들어야 할 경우가 있다.
# 이때는 크기 0인 배열을 생성하고 append()를 수행한다.

import numpy as np
A=np.array([])
for i in range(3):
  A=np.append(A,[1,2,3])
A

array([1., 2., 3., 1., 2., 3., 1., 2., 3.])

In [ ]:
A.dtype

dtype('float64')

In [ ]:
# shape과 dtype 변경
# ndarray는 고정된 크기를 유지하면서 shape을 변경할 수 있다.
# (9,) -> (3,3)
# reshape() 함수를 이용하여 변경할 수 있다.
x=np.arange(0,9,1.)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
y=np.reshape(x,(3,3))
y

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
# 만약 자기 자신을 대상으로 변경하면 shape 속성을 강제로 변경하면 된다.
x.shape=(3,3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
# astype() 메서드를 사용하면 배열에서 dtype을 바꿀 수 있다.
a=np.arange(3);
a.astype(int)

array([0, 1, 2])

In [ ]:
a.astype('int64')

array([0, 1, 2])

In [ ]:
a.astype('float64')

array([0., 1., 2.])



---

# **인덱싱과 합치기**


In [ ]:
# ndarray에서 인덱싱하는 것은 A[2], A[2,3]등과 같은 [] 연산자를 사용
# A[1:3,1:2]등과 같이 :를 이용한 범위 지정을 통해 부분 배열을 얻어낸다.
a=np.array([1.2,-1.3,2.2,5.3,3.7])
a

array([ 1.2, -1.3,  2.2,  5.3,  3.7])

In [ ]:
a[0]

1.2

In [ ]:
a[0:3]

array([ 1.2, -1.3,  2.2])

In [ ]:
a[-1]

3.7

In [ ]:
a[-2]

5.3

In [ ]:
a[0:-1]

array([ 1.2, -1.3,  2.2,  5.3])

In [ ]:
a=np.array([1.2,-1.3,2.2,5.3,3.7])
idx=[0,3]
a[idx]

array([1.2, 5.3])

**불린 배열**

True와 False로 구성된 boolean array 역시 인덱스 배열처럼 사용가능.
아래 코드에서 x>2와 같이 ndarray에 조건식을 부과하면 boolean array가 계산된다.

In [ ]:
x=np.array([1.2,-1.3,0.,2.2,0.,5.3,3.7])
x[x>2]

array([2.2, 5.3, 3.7])

In [ ]:
x=np.array([1.2,-1.3,0.,2.2,0.,5.3,3.7])
x>2

array([False, False, False,  True, False,  True,  True])

In [ ]:
idx=x>2
idx

array([False, False, False,  True, False,  True,  True])

In [ ]:
x[idx]

array([2.2, 5.3, 3.7])

In [ ]:
# np.nonzero(x)는 배열 x의 원소가 0이 아닌 인덱스를 배열형태로 리턴해주는 함수.
x=np.array([1.2,-1.3,0.,2.2,0.,5.3,3.7])
np.nonzero(x)

(array([0, 1, 3, 5, 6]),)

In [ ]:
x=np.array([1.2,-1.3,0.,2.2,0.,5.3,3.7])
np.nonzero(x>2)

(array([3, 5, 6]),)

In [ ]:
# 합치기
# concatenate((A,B,...),axis=0), hstack((A,B,...)),vstack((A,B,...))
# 위의 함수를 통해 배열을 합칠 수 있다.
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.concatenate((a,b),axis=0) # 행으로 추가

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a,b.T),axis=1) # 열로 추가

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
# 2차원 행렬을 대상으로 한다면 hstack나 vstack이 더 편리하다.
a=np.array([1,2,3])
b=np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
c=np.append(a,b)

In [ ]:
c

array([1, 2, 3, 4, 5, 6])

In [ ]:
b=np.array([5,6]) # 1차원 배열
b.shape # 위에서 1차원 배열의 형태였으면 에러 발생.

(2,)

In [ ]:
b=np.array([[5,6]]) # 2차원 배열
b.shape

(1, 2)

# **연산**

In [ ]:
# ndarray 객체에 대한 연산은 기본적으로 elementwise로 진행된다.
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [ ]:
a*b

array([ 4, 10, 18, 28])

In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
10*np.sin(a)

array([ 8.41470985,  9.09297427,  1.41120008, -7.56802495])

In [ ]:
a<3

array([ True,  True, False, False])

In [ ]:
a*=b

In [ ]:
a

array([ 1024,  6250, 23328, 67228])

In [ ]:
# 위와 같이 배열의 개별 요소가 아닌 배열에 대해 연산을 적용하는 것을 vectorization이라 하며
# 크기가 다를 경우에도 작동하도록 한 것을 broadcasting이라고 한다.

# Universal 함수
x=np.arange(0.,2*np.pi,0.1)
y=np.sin(x)
y

array([ 0.        ,  0.09983342,  0.19866933,  0.29552021,  0.38941834,
        0.47942554,  0.56464247,  0.64421769,  0.71735609,  0.78332691,
        0.84147098,  0.89120736,  0.93203909,  0.96355819,  0.98544973,
        0.99749499,  0.9995736 ,  0.99166481,  0.97384763,  0.94630009,
        0.90929743,  0.86320937,  0.8084964 ,  0.74570521,  0.67546318,
        0.59847214,  0.51550137,  0.42737988,  0.33498815,  0.23924933,
        0.14112001,  0.04158066, -0.05837414, -0.15774569, -0.2555411 ,
       -0.35078323, -0.44252044, -0.52983614, -0.61185789, -0.68776616,
       -0.7568025 , -0.81827711, -0.87157577, -0.91616594, -0.95160207,
       -0.97753012, -0.993691  , -0.99992326, -0.99616461, -0.98245261,
       -0.95892427, -0.92581468, -0.88345466, -0.83226744, -0.77276449,
       -0.70554033, -0.63126664, -0.55068554, -0.46460218, -0.37387666,
       -0.2794155 , -0.1821625 , -0.0830894 ])

In [ ]:
import numpy as np
A=np.arange(9).reshape(3,3)
B=np.arange(11,11+9).reshape(3,3)

x=np.arange(3)
y=np.arange(3).reshape(3,1)
z=np.arange(3).reshape(1,3)

C1=np.dot(A,B)
C2=np.matmul(A,B)
C3=A@B


In [ ]:
import numpy as np
x=np.array([9.1,8.2,2.3,3,3,7.6,5.2])
np.amin(x)

2.3

In [ ]:
np.amax(x)

9.1

In [ ]:
np.argmin(x)

2

In [ ]:
np.argmax(x)

0

In [ ]:
np.sort(x)

array([2.3, 3. , 3. , 5.2, 7.6, 8.2, 9.1])

In [ ]:
np.argsort(x)

array([2, 3, 4, 6, 5, 1, 0])

In [ ]:
# 만약 두 번째로 큰 값의 위치를 구한다면 다음과 같다.
imax2=np.argsort(x)[-2]



---



---



The Numpy library is the core library for scientific computing in python.

It provides a high-performance multidimensional array object, and tools for working with these arrays.

Use the following import conventions:

**import numpy as np**

In [5]:
import numpy as np

# Creating Arrays
a=np.array([1,2,3])
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [13]:
# Create an array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# Create an array of ones
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
# Create an array of evenly spaced values(step value)
d=np.arange(10,25,5)

In [11]:
print(d)

[10 15 20]


In [18]:
# Create an array of evenly spaced values(number of samples)
np.linspace(0,2,9) # 0부터 2까지 9등분하기.

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [28]:
# Create a constant array
e=np.full((2,2),8) # (2,2)에 어떤 값을 넣어도 2x2배열이 만들어짐. 뭐지?

In [26]:
print(e)

[[8 8]
 [8 8]]


In [30]:
# Create a 2x2 identity matrix
f=np.eye(2)

In [31]:
print(f)

[[1. 0.]
 [0. 1.]]


In [32]:
# Create an array with random values
np.random.random((2,2))

array([[0.91616301, 0.09061999],
       [0.37581731, 0.4812271 ]])

In [37]:
# Create an empty array
np.empty((3,2)) # empty 아닌데?

array([[4.67982524e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

### **Inspecting Your Array**

In [38]:
# Array dimensions
a.shape

(3,)

In [39]:
# Length of array
len(a)

3

In [40]:
# Number of array dimensions 배열의 차원을 알려준다.
b.ndim

2

In [41]:
a.ndim

1

In [42]:
c.ndim

3

In [43]:
# Number of array elements
e.size

4

In [45]:
# Data type of array elements
b.dtype

dtype('float64')

In [46]:
# Name of data type
b.dtype.name

'float64'

In [47]:
# Convert an array to a different type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
b.astype(float)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### **Sorting Arrays**

In [49]:
a.sort()

In [54]:
# Sort the elements of an array's axis
c.sort(axis=0)

In [53]:
print(c)

[[[1.5 2.  1. ]
  [4.  5.  6. ]]

 [[3.  2.  3. ]
  [4.  5.  6. ]]]


### **Subsetting, Slicing, Indexing**

In [56]:
a=np.array([1,2,3])
b=np.array([[1.5,2,3],[4,5,6]])

# Subsetting
# 가냥 단순히 배열의 요소를 인덱스를 이용해 뽑아내는 것.
a[2]

3

In [59]:
b[1,2]

6.0

In [60]:
# Slicing
a[0:2] # easy

array([1, 2])

In [63]:
# Select items at rows 0 and 1 in column 1 # row=행, column=열
b[0:2,1] # 인덱스 1인 열에 0,1의 행 인덱스에 있는 값을 뽑아냄.

array([2., 5.])

In [64]:
# Select all items at row 0 (same as b[0:1, :])
b[:1]

array([[1.5, 2. , 3. ]])

In [65]:
# Same as [1,:,:]
c[1,...]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [68]:
# Reversed array a
a[::-1]

array([3, 2, 1])

### **Array Manipulation**

In [72]:
# Transposing Array
# Permute array dimensions
i=np.transpose(b)

In [71]:
# Permute array dimensions
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [73]:
# Changing Array Shape
# Flatten the array
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [75]:
# Reshape, but don't change data
i.reshape(3,-2)

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [81]:
# Adding/Removing Elements
# Return a new array with shape(2,6)
c.resize((2,6))

In [82]:
# Append items to an array
np.append(a,b)

array([1. , 2. , 3. , 1.5, 2. , 3. , 4. , 5. , 6. ])

In [83]:
# Insert items in an array
np.insert(a,1,5)

array([1, 5, 2, 3])

In [84]:
# Delete items form an array
np.delete(a,[1])

array([1, 3])

In [88]:
# Combining Arrays
# Concatenate arrays
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [89]:
# Stack arrays vertically (row-wise)
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [90]:
# Stack arrays vertically (row-wise)
np.r_[e,f]

array([[8., 8.],
       [8., 8.],
       [1., 0.],
       [0., 1.]])

In [91]:
# Stack arrays horizontally (column-wise)
np.hstack((e,f))

array([[8., 8., 1., 0.],
       [8., 8., 0., 1.]])

In [93]:
# Create stacked column-wise arrays
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [94]:
# Create stacked column-wise arrays
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])